### PR TITLE
add coverage tip to readme

### PR DESCRIPTION
**Pull request by mlctrez**

### CODE REVIEW

**Comment by agnivade** [comment]
There's some unncessary env variables being injected in the windows runs. Will need to take a look.

**Comment by mlctrez** [comment]
> There's some unncessary env variables being injected in the windows runs. Will need to take a look.

I took a look and found a few that could be excluded:
https://github.com/agnivade/wasmbrowsertest/pull/53

**Comment by agnivade** [comment]
@mlctrez - Could you rebase latest master on this? I think we would be good to merge after that. Thanks.

**Comment by mlctrez** [comment]
@agnivade This should be good to go now.

**Comment by agnivade** [comment]
I don't see a commit yet. Did you push the branch?

**Comment by mlctrez** [comment]
@agnivade missed a step, I don't work with forks enough.  It is there now.

**Pull request merged**
