### PR TITLE
replace flag.Parse with gentleParse

### PR DESCRIPTION
**Pull request by FrankReh**
gentleParse does away with having to call out all the arguments that
will be passed to the wasm image.

Now the wasm image will be passed all the arguments that the tool
doesn't recognize itself.

Also there are unit test examples of the parsing.

### CODE REVIEW

**Comment by FrankReh** [comment]
Per issue #33

**Comment by agnivade** [comment]
Sorry for the delay here @FrankReh. I've been meaning to get to this but haven't got a chance yet. Hopefully this weekend I'll be able to look at it. Thanks for your patience!

**Review by agnivade — COMMENTED** [review]
@FrankReh - Starting to review this now. The code doesn't seem to handle `=` to pass the flag value. By default several std lib options are passed as `=` and it fails with the "pull not found error". This line `for next[0] != pull` does not match and then it tries to take the next value and fails.

I think after trimming the prefix, we'd need to split by "=" and then do the check.

Couple of other review comments:
1. Let's move gentleParse to parse.go
2. Move the const prefix to outside the loop.
3. Change the tests to write to a `bytes.Buffer` and check the output. Yes, this needs some addtional helper to match the slices, but it's more idiomatic.

Thanks for taking on this!

**Comment by FrankReh** [comment]
Yes to all. Good catch on the "=" case. I actually ran into that yesterday
and was wondering if I was going to be able to fix my PR before you looked
at it. I should be able to do the other suggestions as well. It's been
years since I used a PR in github so I'm not sure but I assume when I push
changes up to the same branch, they will make it to the PR you are viewing.
We'll see.

**Comment by FrankReh** [comment]
Did you mean replace the test Example functions?

**Comment by FrankReh** [comment]
Example functions are replaced with more standard Test functions. If you would like them combined into a single Test function that iterates through the examples, I can do that easily too.

**Review by agnivade — APPROVED** [review]
The tests and variable names can be improved slightly, but I can do those myself. There is some other unrelated issue with Chrome itself which is preventing me from running the tool. I'll have to take a look.

Thanks for doing this!

**Comment by FrankReh** [comment]
Okay. Thanks for the update. 

-Frank

**Pull request merged**
